config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  resources :users
  resources :comments

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', :via => :delete
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :body

  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :url
  validates_presence_of :title

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :username
  validates_presence_of :name

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      return User.find_by(id: session[:user_id])
    else
      return nil
    end
  end

def logged_in?
  session[:user_id]
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:comment][:post_id])
    comment = post.comments.build(comment_params)
    if comment.save
      comment.update_attributes(user_id: session[:user_id])
    else
      flash[:invalid_comment] = "missing field in comment forms, try again"
    end
    redirect_to "/posts/#{post.id}"
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    post = @comment.post
    @comment.update(comment_params)
    redirect_to post_path(post.id)
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = @comment.post
    @comment.destroy
    redirect_to post_path(post.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
      respond_to do |fmt|
        fmt.html
        fmt.json { render json: @posts.to_json } ## Fun!!
      end
  end

  def new
    @post = Post.new
  end

  def create
    user = User.find_by(id: session[:user_id])
    post = user.posts.build(post_params)
    if post.save
      redirect_to '/'
    else
      flash[:error] = "post did not save, please try again."
      redirect_to '/posts/new'
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    post = Post.find_by(id: params[:id])
    if post.update(post_params)
      redirect_to '/'
    else
      flash[:invalid_edit_field] = "Invalid field in the edit box, please try again"
      redirect_to edit_post_path(post)
    end
  end

  def destroy
    post = Post.find_by(id: params[:id])
    post.destroy
    redirect_to '/'
  end

  def show
    @post = Post.find_by(id: params[:id])
    @new_comment = Comment.new
  end

  private
  def post_params
    params.require(:post).permit(:url, :title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(username: params[:user][:username])
    if user
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:invalid_login] = "Unable to find password & username combination"
      redirect_to '/users/new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:alert] = "You already exist, please login"
      redirect_to '/login'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment_form.html.erb
<%= form_for comment do |f| %>
  <%= f.text_area :body, cols: 40, rows: 10 %><br>
  <%= f.hidden_field :post_id, :value => post.id %>
  <%= f.submit "Add comment" %>
<% end %>

app/views/comments/edit.html.erb
<%= form_for @comment do |f| %>
  <%= f.text_field :body, placeholder: "Body" %>
  <%= f.submit "Update" %>
<% end %>

app/views/layouts/_header.html.erb
<div id="wrapper">
  <div id="menu-wrapper">
    <div id="menu">
      <ul>
        <li class="current_page_item"><%= link_to "[ Y ]", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Create Post", new_post_path %></li>
          <li><%= link_to "Logout", logout_path, method: :delete, id: "logout-link" %></li>
        <% else %>
          <li><%= link_to "login", '/login' %></li>
          <li><%= link_to "register", '/users/new' %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div id="header-wrapper">
    <% if logged_in? %>
      <h4> Welcome <%= current_user.name %> to Hacker(ish) News!</h4>
    <% else %>
      <h4>Welcome to Hacker(ish) News</h4>
    <% end %>
  </div>
</div>
<div class="container">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "layouts/header" %>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: name %>
<% end %>
<%= yield %>
</div>

</body>
</html>

app/views/posts/_comment.html.erb
<li>
  <%= comment.body %>
  <h6>written by <%=comment.user.username%> <%= time_ago_in_words(comment.created_at) %></h6>
  <% if current_user == comment.user %>
    <%= link_to "Edit", edit_comment_path(comment.id) %>
    <%= link_to "Delete", comment_path(comment.id), method: :delete %>
  <% end %>
</li>
<br><br>

app/views/posts/_show.html.erb
<li>
  <%= link_to post.title, post.url %>
  <%= link_to post.comments.count, post_path(post.id) %> comments
  <br>
  <% if current_user == post.user %>
    <%= link_to "edit", edit_post_path(post.id) %>
    <%= link_to "delete", post_path(post.id), method: :delete %>
  <% end %>
</li>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%= f.text_field :url, placeholder: "URL" %>
  <%= f.text_field :title, placeholder: "Title" %>
  <%= f.submit "Create" %>
<% end %>

app/views/posts/index.html.erb
<ol>
  <% @posts.each do |post| %>
    <%= render partial: "posts/show", locals: {post: post} %>
  <% end %>
</ol>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.text_field :url, placeholder: "URL" %>
  <%= f.text_field :title, placeholder: "Title" %>
  <%= f.submit "Create" %>
<% end %>

app/views/posts/show.html.erb
<br><%= @post.title %>(<%=@post.url%>)<br>

<h6>written by <%=@post.user.username%> <%= time_ago_in_words(@post.created_at) %></h6>

<% if logged_in? %>
  <%= render partial: "comments/comment_form", locals: {comment: @new_comment, post: @post} %>
<% else %>
  <%= link_to "login to leave a comment", '/login' %>
<% end %>

<ol>
  <% @post.comments.each do |comment| %>
    <%= render partial: "posts/comment", locals: {comment: comment} %>
  <% end %>
</ol>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
  <%= f.text_field :username, placeholder: "Username" %>
  <%= f.password_field :password, placeholder: "Password" %>
  <br>
  <%= f.submit "Register" %>
<% end %>